# Generated by Django 3.0.11 on 2020-11-05 06:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bellboy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellboydevice',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='bellboy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='bellboy.BellboyDevice', to_field='identifier'),
        ),
    ]
